import type TableColumn from '@/classes/table-column.class';
import type { Meta } from '@/components/TableComponent.vue';
import type { Column } from '@/interfaces/column.interface';
import type { TableRow } from '@/interfaces/table-row.interface';

type test = { gf: ''; fsd: '' };

const columns: Column[] = [
  {
    name: 'ID',
    cssClass: '',
    columnType: 'number',
    caption: '№ \n fdsf',
    rendered: true,
    editable: false,
    formating: { disable: true },
    width: 70,
    excludeFromTotals: true,
    templating: {
      cellHtml(rowData, column, formatEd, formatRazryad, meta) {
        return `<h3>${rowData[column.name]}</h3>`;
      },
    },
  },
  {
    name: 'outside_None',
    cssClass: '',
    columnType: 'boolean',
    caption: 'Сторонние/Группа для Формуляра ',
    rendered: true,
    trueValue: 'Группа/Корпоративные НИПИ',
    falseValue: 'Сторонние',
    editable: false,
  },
  {
    name: 'customer_Staff_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Контрагент',
    rendered: true,
    editable: true,
  },
  {
    name: 'techCustomer_Staff_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Технический заказчик',
    rendered: true,
    editable: true,
    width: 100,
  },

  {
    name: 'numberContract_None',
    cssClass: '',
    columnType: 'string',
    caption: 'Номер договора',
    rendered: true,
    editable: true,
    width: 150,
    validation: {
      isReqired: true,
    },
  },
  {
    name: 'name_CalendarPlan',
    cssClass: '',
    columnType: 'string',
    caption: 'Наименование работ',
    rendered: true,
    editable: true,
    width: 200,
  },

  {
    name: 'internalOrder_CalendarPlan',
    cssClass: '',
    columnType: 'string',
    caption: 'Внутренние заказы',
    rendered: true,
    editable: true,
    width: 100,
  },

  {
    name: 'contractsDates',
    cssClass: '',
    columnType: 'joined',
    caption: 'Дата заключения договора',
    rendered: true,
    editable: false,
    child: [
      {
        name: 'dateConclusionContractFact_CalendarPlan',
        cssClass: '',
        columnType: 'datetime',
        caption: 'Факт ',
        rendered: true,
        editable: true,
        width: 100,
        validation: {
          isReqired: true,
        },
      },
      {
        name: 'dateConclusionContractPlan_CalendarPlan',
        cssClass: '',
        columnType: 'date',
        caption: 'План ',
        rendered: true,
        editable: true,
        width: 100,
      },
    ],
  },
  {
    name: 'statusCalendarPlan_None',
    cssClass: '',
    columnType: 'enum',
    caption: 'Статус договора',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'contractsPeriod',
    cssClass: '',
    columnType: 'joined',
    caption: 'Срок действия договора',
    rendered: true,
    editable: true,
    child: [
      {
        name: 'start_CalendarPlan',
        cssClass: '',
        columnType: 'date',
        caption: 'Начало работ по договору',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'finish_CalendarPlan',
        cssClass: '',
        columnType: 'date',
        caption: 'Окончание работ по договору',
        rendered: true,
        editable: true,
        width: 100,
      },
    ],
  },

  {
    name: 'status_CommentBlock',
    cssClass: '',
    columnType: 'string',
    caption: 'Комментарий по ст. работ по закл. ГД',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'genwork_CalendarPlan',
    cssClass: '',
    columnType: 'boolean',
    caption: 'Ген/Суб',
    trueValue: 'Генподряд',
    falseValue: 'Субподряд',
    rendered: true,
    editable: false,
    defaultValue: true,
    width: 100,
  },
  {
    name: 'department_Staff_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Управление',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'curator_None',
    cssClass: '',
    columnType: 'enum',
    caption: 'Куратор',
    rendered: true,
    editable: false,
    width: 100,
  },
  {
    name: 'kindWork_Business_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Вид работ',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'directWork_Business_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Направление работ',
    rendered: true,
    editable: true,
    width: 100,
  },

  {
    name: 'risk_CalendarPlan',
    cssClass: '',
    columnType: 'boolean',
    caption: 'Риск',
    trueValue: 'Да',
    falseValue: 'Нет',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'ndsId_CalendarPlan',
    cssClass: '',
    columnType: 'enum',
    caption: 'НДС',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'totalContract_CalendarPlan',
    cssClass: '',
    columnType: 'number',
    caption: 'Всего по договору',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'opex_CalendarPlan',
    cssClass: '',
    columnType: 'boolean',
    caption: 'OPEX/CAPEX',
    rendered: true,
    editable: true,
    trueValue: 'OPEX',
    falseValue: 'CAPEX',
    width: 100,
  },
  {
    name: 'general_CommentBlock',
    cssClass: '',
    columnType: 'string',
    caption: 'Комментарии',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'indexes',
    cssClass: '',
    columnType: 'joined',
    caption: 'Показатели',
    rendered: true,
    editable: false,
  },

  {
    name: 'growingTotalBp',
    cssClass: '',
    columnType: 'joined',
    caption: 'Нараст.итог по отклонениям факт/ожидание от БП',
    rendered: true,
    editable: false,
    child: [
      {
        name: 'growingTotalBpBp',
        cssClass: 'index-color-dark-blue ',
        columnType: 'joined',

        caption: 'БП (без начисл.выр)',
        rendered: true,
        editable: false,
        child: [
          {
            name: 'growingTotalBpBpGen',
            cssClass: 'index-color-blue',
            columnType: 'computed',
            caption: 'Генподряд ',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpBpSS',
            cssClass: 'index-color-orange',
            columnType: 'computed',
            caption: 'Соб.силы ',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpBpSub',
            cssClass: 'index-color-green ',
            columnType: 'computed',
            caption: 'Субподряд ',
            rendered: true,
            editable: false,
            width: 100,
          },
        ],
      },
      {
        name: 'growingTotalBpFactPlan',
        cssClass: 'index-color-dark-blue ',
        columnType: 'joined',

        caption: 'Факт/текущий прогноз',
        rendered: true,
        editable: false,
        child: [
          {
            name: 'growingTotalBpFactPlanGen',
            cssClass: 'index-color-blue',
            columnType: 'computed',
            caption: 'Генподряд ',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpFactPlanSS',
            cssClass: 'index-color-orange',
            columnType: 'computed',
            caption: 'Соб.силы',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpFactPlanSub',
            cssClass: 'index-color-green ',
            columnType: 'computed',
            caption: 'Субподряд ',
            rendered: true,
            editable: false,
            width: 100,
            computing: {
              value: (
                rowData: TableRow,
                column: Column,
                ed: number,
                raz: number,
                meta?: Meta,
              ) => {
                return `Вычисленное значение ${rowData['ID']}`;
              },
            },
          },
        ],
      },
      {
        name: 'growingTotalBpDiff',
        cssClass: 'index-color-dark-blue ',
        columnType: 'joined',

        caption: 'Разница ФАКТ/БП',
        rendered: true,
        editable: false,
        child: [
          {
            name: 'growingTotalBpDiffGen',
            cssClass: 'index-color-blue',
            columnType: 'computed',
            caption: 'Генподряд ',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpDiffSS',
            cssClass: 'index-color-orange',
            columnType: 'computed',
            caption: 'Соб.силы ',
            rendered: true,
            editable: false,
            width: 100,
          },
          {
            name: 'growingTotalBpDiffSub',
            cssClass: 'index-color-green ',
            columnType: 'computed',
            caption: 'Субподряд ',
            rendered: true,
            editable: false,
            width: 100,
          },
        ],
      },
    ],
  },
  {
    name: 'deviationPlan_CommentBlock',
    cssClass: '',
    columnType: 'string',
    caption:
      'Причина отклонения факта/ожида от БП (без начисленной выручки) за отчет.период',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'diffTotalFactor',
    cssClass: 'index-color-blue',
    columnType: 'joined',
    caption:
      'Изменение общей выручки от БП (без начисленной выручки) за счет факторов',
    rendered: true,
    editable: false,
    width: 100,
    child: [
      {
        name: 'diffTotalWithoutNDS',
        cssClass: 'index-color-blue',
        columnType: 'computed',
        caption: 'Отклонение ВСЕГО, тыс. руб. без НДС',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'discountEconomySelf_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption: 'Скидка Заказчикам за счет экономии собственных средств',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'cancellWork_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption: 'Отмена объемов работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'transferWork_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption:
          'Перенос на следующий год объемов работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'revisionWork_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption:
          'Уточнение состава/ объемов работ / Доп.объемы работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'closeCosts_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption: 'Закрытие по факт. Затратам',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'reduceTender_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption: 'Снижение стоимости работ за счет тендеров по с/п',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'operationKNIPI_GeneralForcesFactor',
        cssClass: 'index-color-blue',
        columnType: 'number',
        caption: 'По результатам деятельности КНИПИ',
        rendered: true,
        editable: true,
        width: 100,
      },
    ],
  },
  {
    name: 'comments_GeneralForcesFactor',
    cssClass: 'index-color-blue',
    columnType: 'string',
    caption:
      'Комментарии по изменению общей выручки от БП (без начисленной выручки)',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'diffTotalFactorSS',
    cssClass: 'index-color-orange',
    columnType: 'joined',
    caption: 'Изменение собств. сил/субподряда  за счет факторов',
    rendered: true,
    editable: false,
    width: 100,
    child: [
      {
        name: 'diffTotalWithoutNDSSS',
        cssClass: 'index-color-orange',
        columnType: 'computed',
        caption: 'Отклонение ВСЕГО, тыс. руб. без НДС',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'discountEconomySelf_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption: 'Скидка Заказчикам за счет экономии собственных средств',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'cancellWork_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption: 'Отмена объемов работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'transferWork_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption:
          'Перенос на следующий год объемов работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'revisionWork_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption:
          'Уточнение состава/ объемов работ / Доп.объемы работ по инициативе Заказчика',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'moveSelf_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption: 'Отмена с/п, выполнение их с/с',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'operationKNIPI_OwnForcesFactor',
        cssClass: 'index-color-orange',
        columnType: 'number',
        caption: 'По результатам деятельности КНИПИ',
        rendered: true,
        editable: true,
        width: 100,
      },
    ],
  },
  {
    name: 'comments_OwnForcesFactor',
    cssClass: 'index-color-orange',
    columnType: 'string',
    caption:
      'Комментарии по изменению собств. сил от БП (без начисленной выручки)',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'techCustomerDepartment_Staff_Project',
    cssClass: '',
    columnType: 'enum',
    caption: 'Технический заказчик',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'cIP_GhostCalendarPlan',
    cssClass: '',
    columnType: 'string',
    caption: 'ЦИП',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'timeConstraints_GhostCalendarPlan',
    cssClass: '',
    columnType: 'date',
    caption: 'Срок окончания работ',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'monitoringUnplannedWork_GhostCalendarPlan',
    cssClass: '',
    columnType: 'enum',
    caption: 'Мониторинг внеплановых объемов для ГИРов',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'uniqueIdNumberOfYear_NumberCalendarPlanOfYear',
    cssClass: '',
    columnType: 'string',
    caption: 'Уникальный идентификационный номер',
    rendered: true,
    editable: false,
    width: 100,
  },
  {
    name: 'formatGeneralContractOutsideCustomer_None',
    cssClass: '',
    columnType: 'enum',
    caption: 'Формат заключения генподрядного договора со сторонним заказчиком',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'reasonOfExternalSubwork',
    cssClass: 'index-color-green',
    columnType: 'joined',
    caption: 'ОБОСНОВАНИЕ ПЕРЕДАЧИ РАБОТЫ НА ВНЕШНИЙ СУБПОДРЯД',
    rendered: true,
    editable: false,
    width: 100,
    child: [
      {
        name: 'completeMailKNIPI_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'string',
        caption: 'В какие КНИПИ выполнена рассылка',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'dateMailCommercialOffer_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'date',
        caption: 'Дата рассылки ТКП',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'refusalKNIPI_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'string',
        caption: 'КНИПИ с отказами',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'reasonTransferExternalSub_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'string',
        caption: 'Обоснование передачи на внешний субподряд ',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'contractConclusionFormat_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'string',
        caption: 'Формат заключения договора',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'approveGI_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'boolean',
        caption: 'Согласование ГИ',
        trueValue: 'Да',
        falseValue: 'Нет',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'approveDPR_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'boolean',
        caption: 'Согласование ДПР',
        trueValue: 'Да',
        falseValue: 'Нет',
        rendered: true,
        editable: true,
        width: 100,
      },
      {
        name: 'comments_ReasonTransferWorkExternalSub',
        cssClass: 'index-color-green',
        columnType: 'string',
        caption: 'Комментарии',
        rendered: true,
        editable: true,
        width: 100,
      },
    ],
  },
  {
    name: 'scopeWorkSubcontract_None',
    cssClass: '',
    columnType: 'enum',
    caption: 'Объем работ договора, передаваемых на субподряд работ',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'reasonWorkSubcontract_None',
    cssClass: ' ',
    columnType: 'enum',
    caption:
      'Причины передачи объемов работ для выполнения на субподряд в текущем году',
    rendered: true,
    editable: true,
    width: 100,
  },
  {
    name: 'numberContractId_CalendarPlan',
    cssClass: '',
    columnType: 'string',
    caption: 'ID Номера договора',
    rendered: false,
    editable: true,
    width: 0,
  },
  {
    name: 'parentId_CalendarPlan',
    cssClass: '',
    columnType: 'string',
    caption: 'ID генподряда',
    rendered: false,
    editable: false,
    width: 0,
  },
];

export default columns;
