export interface SuppEconomicCapexReport {
  OrderRow: number
  code: string
  codeeconomica: string
  color: string
  level: number
  name: string
  total1: number
  total2: number
  total3: number
  total4: number
  total5: number
  total6: number
  total7: number
  total8: number
  total9: number
  total10: number
  total11: number
  total12: number
  totaltotal: number
  bptotal: number
  reg_geo1opex: number
  reg_geo2opex: number
  reg_geo3opex: number
  reg_geo4opex: number
  reg_geo5opex: number
  reg_geo6opex: number
  reg_geo7opex: number
  reg_geo8opex: number
  reg_geo9opex: number
  reg_geo10opex: number
  reg_geo11opex: number
  reg_geo12opex: number
  totalreg_geoopex: number
  bpreg_geoopex: number
  reg_geo1capex: number
  reg_geo2capex: number
  reg_geo3capex: number
  reg_geo4capex: number
  reg_geo5capex: number
  reg_geo6capex: number
  reg_geo7capex: number
  reg_geo8capex: number
  reg_geo9capex: number
  reg_geo10capex: number
  reg_geo11capex: number
  reg_geo12capex: number
  totalreg_geocapex: number
  bpreg_geocapex: number
  ptd_pz1opex: number
  ptd_pz2opex: number
  ptd_pz3opex: number
  ptd_pz4opex: number
  ptd_pz5opex: number
  ptd_pz6opex: number
  ptd_pz7opex: number
  ptd_pz8opex: number
  ptd_pz9opex: number
  ptd_pz10opex: number
  ptd_pz11opex: number
  ptd_pz12opex: number
  totalptd_pzopex: number
  bpptd_pzopex: number
  ptd_pz1capex: number
  ptd_pz2capex: number
  ptd_pz3capex: number
  ptd_pz4capex: number
  ptd_pz5capex: number
  ptd_pz6capex: number
  ptd_pz7capex: number
  ptd_pz8capex: number
  ptd_pz9capex: number
  ptd_pz10capex: number
  ptd_pz11capex: number
  ptd_pz12capex: number
  totalptd_pzcapex: number
  bpptd_pzcapex: number
  lab_isl1opex: number
  lab_isl2opex: number
  lab_isl3opex: number
  lab_isl4opex: number
  lab_isl5opex: number
  lab_isl6opex: number
  lab_isl7opex: number
  lab_isl8opex: number
  lab_isl9opex: number
  lab_isl10opex: number
  lab_isl11opex: number
  lab_isl12opex: number
  totallab_islopex: number
  bplab_islopex: number
  lab_isl1capex: number
  lab_isl2capex: number
  lab_isl3capex: number
  lab_isl4capex: number
  lab_isl5capex: number
  lab_isl6capex: number
  lab_isl7capex: number
  lab_isl8capex: number
  lab_isl9capex: number
  lab_isl10capex: number
  lab_isl11capex: number
  lab_isl12capex: number
  totallab_islcapex: number
  bplab_islcapex: number
  niokr1opex: number
  niokr2opex: number
  niokr3opex: number
  niokr4opex: number
  niokr5opex: number
  niokr6opex: number
  niokr7opex: number
  niokr8opex: number
  niokr9opex: number
  niokr10opex: number
  niokr11opex: number
  niokr12opex: number
  totalniokropex: number
  bpniokropex: number
  niokr1capex: number
  niokr2capex: number
  niokr3capex: number
  niokr4capex: number
  niokr5capex: number
  niokr6capex: number
  niokr7capex: number
  niokr8capex: number
  niokr9capex: number
  niokr10capex: number
  niokr11capex: number
  niokr12capex: number
  totalniokrcapex: number
  bpniokrcapex: number
  concept1opex: number
  concept2opex: number
  concept3opex: number
  concept4opex: number
  concept5opex: number
  concept6opex: number
  concept7opex: number
  concept8opex: number
  concept9opex: number
  concept10opex: number
  concept11opex: number
  concept12opex: number
  totalconceptopex: number
  bpconceptopex: number
  concept1capex: number
  concept2capex: number
  concept3capex: number
  concept4capex: number
  concept5capex: number
  concept6capex: number
  concept7capex: number
  concept8capex: number
  concept9capex: number
  concept10capex: number
  concept11capex: number
  concept12capex: number
  totalconceptcapex: number
  bpconceptcapex: number
  obust_mest1: number
  obust_mest2: number
  obust_mest3: number
  obust_mest4: number
  obust_mest5: number
  obust_mest6: number
  obust_mest7: number
  obust_mest8: number
  obust_mest9: number
  obust_mest10: number
  obust_mest11: number
  obust_mest12: number
  totalobust_mest: number
  bpobust_mest: number
  ing_iz1: number
  ing_iz2: number
  ing_iz3: number
  ing_iz4: number
  ing_iz5: number
  ing_iz6: number
  ing_iz7: number
  ing_iz8: number
  ing_iz9: number
  ing_iz10: number
  ing_iz11: number
  ing_iz12: number
  totaling_iz: number
  bping_iz: number
  ing_serv_build1: number
  ing_serv_build2: number
  ing_serv_build3: number
  ing_serv_build4: number
  ing_serv_build5: number
  ing_serv_build6: number
  ing_serv_build7: number
  ing_serv_build8: number
  ing_serv_build9: number
  ing_serv_build10: number
  ing_serv_build11: number
  ing_serv_build12: number
  totaling_serv_build: number
  bping_serv_build: number
  proekt_str_skv1: number
  proekt_str_skv2: number
  proekt_str_skv3: number
  proekt_str_skv4: number
  proekt_str_skv5: number
  proekt_str_skv6: number
  proekt_str_skv7: number
  proekt_str_skv8: number
  proekt_str_skv9: number
  proekt_str_skv10: number
  proekt_str_skv11: number
  proekt_str_skv12: number
  totalproekt_str_skv: number
  bpproekt_str_skv: number
  other_prod1: number
  other_prod2: number
  other_prod3: number
  other_prod4: number
  other_prod5: number
  other_prod6: number
  other_prod7: number
  other_prod8: number
  other_prod9: number
  other_prod10: number
  other_prod11: number
  other_prod12: number
  totalother_prod: number
  bpother_prod: number
  other1: number
  other2: number
  other3: number
  other4: number
  other5: number
  other6: number
  other7: number
  other8: number
  other9: number
  other10: number
  other11: number
  other12: number
  totalother: number
  bpother: number
}

export interface SuppEconomicReport {
  OrderRow: number
  code: string
  codeeconomica: string
  color: string
  level: number
  name: string
  total1: number
  total2: number
  total3: number
  total4: number
  total5: number
  total6: number
  total7: number
  total8: number
  total9: number
  total10: number
  total11: number
  total12: number
  totaltotal: number
  bptotal: number
  reg_geo1: number
  reg_geo2: number
  reg_geo3: number
  reg_geo4: number
  reg_geo5: number
  reg_geo6: number
  reg_geo7: number
  reg_geo8: number
  reg_geo9: number
  reg_geo10: number
  reg_geo11: number
  reg_geo12: number
  totalreg_geo: number
  bpreg_geo: number
  ptd_pz1: number
  ptd_pz2: number
  ptd_pz3: number
  ptd_pz4: number
  ptd_pz5: number
  ptd_pz6: number
  ptd_pz7: number
  ptd_pz8: number
  ptd_pz9: number
  ptd_pz10: number
  ptd_pz11: number
  ptd_pz12: number
  totalptd_pz: number
  bpptd_pz: number
  lab_isl1: number
  lab_isl2: number
  lab_isl3: number
  lab_isl4: number
  lab_isl5: number
  lab_isl6: number
  lab_isl7: number
  lab_isl8: number
  lab_isl9: number
  lab_isl10: number
  lab_isl11: number
  lab_isl12: number
  totallab_isl: number
  bplab_isl: number
  niokr1: number
  niokr2: number
  niokr3: number
  niokr4: number
  niokr5: number
  niokr6: number
  niokr7: number
  niokr8: number
  niokr9: number
  niokr10: number
  niokr11: number
  niokr12: number
  totalniokr: number
  bpniokr: number
  concept1: number
  concept2: number
  concept3: number
  concept4: number
  concept5: number
  concept6: number
  concept7: number
  concept8: number
  concept9: number
  concept10: number
  concept11: number
  concept12: number
  totalconcept: number
  bpconcept: number
  obust_mest1: number
  obust_mest2: number
  obust_mest3: number
  obust_mest4: number
  obust_mest5: number
  obust_mest6: number
  obust_mest7: number
  obust_mest8: number
  obust_mest9: number
  obust_mest10: number
  obust_mest11: number
  obust_mest12: number
  totalobust_mest: number
  bpobust_mest: number
  ing_iz1: number
  ing_iz2: number
  ing_iz3: number
  ing_iz4: number
  ing_iz5: number
  ing_iz6: number
  ing_iz7: number
  ing_iz8: number
  ing_iz9: number
  ing_iz10: number
  ing_iz11: number
  ing_iz12: number
  totaling_iz: number
  bping_iz: number
  ing_serv_build1: number
  ing_serv_build2: number
  ing_serv_build3: number
  ing_serv_build4: number
  ing_serv_build5: number
  ing_serv_build6: number
  ing_serv_build7: number
  ing_serv_build8: number
  ing_serv_build9: number
  ing_serv_build10: number
  ing_serv_build11: number
  ing_serv_build12: number
  totaling_serv_build: number
  bping_serv_build: number
  proekt_str_skv1: number
  proekt_str_skv2: number
  proekt_str_skv3: number
  proekt_str_skv4: number
  proekt_str_skv5: number
  proekt_str_skv6: number
  proekt_str_skv7: number
  proekt_str_skv8: number
  proekt_str_skv9: number
  proekt_str_skv10: number
  proekt_str_skv11: number
  proekt_str_skv12: number
  totalproekt_str_skv: number
  bpproekt_str_skv: number
  other_prod1: number
  other_prod2: number
  other_prod3: number
  other_prod4: number
  other_prod5: number
  other_prod6: number
  other_prod7: number
  other_prod8: number
  other_prod9: number
  other_prod10: number
  other_prod11: number
  other_prod12: number
  totalother_prod: number
  bpother_prod: number
  other1: number
  other2: number
  other3: number
  other4: number
  other5: number
  other6: number
  other7: number
  other8: number
  other9: number
  other10: number
  other11: number
  other12: number
  totalother: number
  bpother: number
}
