export interface SuppKindworkReport {
  ID: number
  orders: number
  names: string
  gen_nakopitel_plan: number
  gen_nakopitel_prognoz: number
  gen_nakopitel_diff: number
  gen_nakopitel_diff_percent: number
  gen_nakopitelnext_plan: number
  gen_nakopitelnext_prognoz: number
  gen_nakopitelnext_diff: number
  gen_nakopitelnext_diff_percent: number
  gen_plan: number
  gen_prognoz: number
  gen_diff: number
  gen_diff_percent: number
  gen_complete: number
  gen_process: number
  gen_no_complete: number
  gen_complete_percent: number
  gen_process_percent: number
  gen_no_complete_percent: number
  sub_nakopitel_plan: number
  sub_nakopitel_prognoz: number
  sub_nakopitel_diff: number
  sub_nakopitel_diff_percent: number
  sub_nakopitelnext_plan: number
  sub_nakopitelnext_prognoz: number
  sub_nakopitelnext_diff: number
  sub_nakopitelnext_diff_percent: number
  sub_plan: number
  sub_prognoz: number
  sub_diff: number
  sub_diff_percent: number
  sub_complete: number
  sub_process: number
  sub_no_complete: number
  sub_complete_percent: number
  sub_process_percent: number
  sub_no_complete_percent: number
  own_nakopitel_plan: number
  own_nakopitel_prognoz: number
  own_nakopitel_diff: number
  own_nakopitel_diff_percent: number
  own_nakopitelnext_plan: number
  own_nakopitelnext_prognoz: number
  own_nakopitelnext_diff: number
  own_nakopitelnext_diff_percent: number
  own_plan: number
  own_prognoz: number
  own_diff: number
  own_diff_percent: number
  own_complete: number
  own_process: number
  own_no_complete: number
  own_complete_percent: number
  own_process_percent: number
  own_no_complete_percent: number
}
