export interface SuppSummaryReport {
  orders: number
  ID: number
  names: string
  levels: number
  gen_accum_plan: number
  gen_accum_prognos: number
  gen_accum_diff: number
  gen_next_plan: number
  gen_next_prognos: number
  gen_next_diff: number
  gen_plan: number
  gen_norm: number
  gen_plan_norm: number
  gen_prognos: number
  gen_economic: number
  gen_diff_economic: number
  gen_diff: number
  gen_diff_norm: number
  gen_discount: number
  gen_diff_discount: number
  gen_diff_discount_percent: number
  gen_complete: number
  gen_process: number
  gen_no_complete: number
  gen_complete_percent: number
  gen_process_percent: number
  gen_no_complete_percent: number
  sub_accum_plan: number
  sub_accum_prognos: number
  sub_accum_diff: number
  sub_next_plan: number
  sub_next_prognos: number
  sub_next_diff: number
  sub_plan: number
  sub_norm: number
  sub_plan_norm: number
  sub_prognos: number
  sub_economic: number
  sub_diff_economic: number
  sub_diff: number
  sub_diff_norm: number
  sub_discount: number
  sub_diff_discount: number
  sub_diff_discount_percent: number
  sub_complete: number
  sub_process: number
  sub_no_complete: number
  sub_complete_percent: number
  sub_process_percent: number
  sub_no_complete_percent: number
  own_accum_plan: number
  own_accum_prognos: number
  own_accum_diff: number
  own_next_plan: number
  own_next_prognos: number
  own_next_diff: number
  own_plan: number
  own_norm: number
  own_plan_norm: number
  own_prognos: number
  own_economic: number
  own_diff_economic: number
  own_diff: number
  own_diff_norm: number
  own_discount: number
  own_diff_discount: number
  own_diff_discount_percent: number
  own_norm_diff_percent: number
  own_complete: number
  own_process: number
  own_no_complete: number
  own_complete_percent: number
  own_process_percent: number
  own_no_complete_percent: number
  gen_old_prognos: number
  sub_old_prognos: number
  own_old_prognos: number
}
