/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    CommentModal: typeof import('./src/components/CommentModal.vue')['default']
    CompanyCard: typeof import('./src/components/CompanyCard.vue')['default']
    ContractorCard: typeof import('./src/components/ContractorCard.vue')['default']
    ContractorGroup: typeof import('./src/components/document-card/ContractorGroup.vue')['default']
    CreateDelegationModal: typeof import('./src/components/CreateDelegationModal.vue')['default']
    CreateEmailModal: typeof import('./src/components/CreateEmailModal.vue')['default']
    DelegationCard: typeof import('./src/components/DelegationCard.vue')['default']
    DocumentCard: typeof import('./src/components/DocumentCard.vue')['default']
    DocumentDelegationsCard: typeof import('./src/components/DocumentDelegationsCard.vue')['default']
    EmailCard: typeof import('./src/components/EmailCard.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusCellContent: typeof import('./src/components/StatusCellContent.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    UploadZone: typeof import('./src/components/UploadZone.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    WysiwygEditor: typeof import('./src/components/WysiwygEditor.vue')['default']
  }
}
