export interface ReportRow {
  account_code: string
  bt_id: number
  city_name: string
  class_dp_plan: number
  class_dp_prog: number
  class_hotel_plan: number
  class_hotel_prog: number
  class_transportation_plan: number
  class_transportation_prog: number
  cmd_count_1: number
  cmd_count_10: number
  cmd_count_11: number
  cmd_count_12: number
  cmd_count_2: number
  cmd_count_3: number
  cmd_count_4: number
  cmd_count_5: number
  cmd_count_6: number
  cmd_count_7: number
  cmd_count_8: number
  cmd_count_9: number
  department_name: string
  exp_plan_price_1: number
  exp_plan_price_10: number
  exp_plan_price_11: number
  exp_plan_price_12: number
  exp_plan_price_2: number
  exp_plan_price_3: number
  exp_plan_price_4: number
  exp_plan_price_5: number
  exp_plan_price_6: number
  exp_plan_price_7: number
  exp_plan_price_8: number
  exp_plan_price_9: number
  exp_plan_price_q1: number
  exp_plan_price_q2: number
  exp_plan_price_q3: number
  exp_plan_price_q4: number
  exp_prog_price_1: number
  exp_prog_price_10: number
  exp_prog_price_11: number
  exp_prog_price_12: number
  exp_prog_price_2: number
  exp_prog_price_3: number
  exp_prog_price_4: number
  exp_prog_price_5: number
  exp_prog_price_6: number
  exp_prog_price_7: number
  exp_prog_price_8: number
  exp_prog_price_9: number
  exp_prog_price_q1: number
  exp_prog_price_q2: number
  exp_prog_price_q3: number
  exp_prog_price_q4: number
  f_s_block: string
  f_s_code: string
  fs: number
  goal_name: string
  mvz_code: string
  need_avia_plan: string
  need_avia_prog: string
  need_count_plan: number
  need_count_prog: number
  need_end_date_plan: string
  need_end_date_prog: string
  need_grade: string
  need_h_price_plan: number
  need_h_price_prog: number
  need_nights_count_plan: number
  need_nights_count_prog: number
  need_overseas_days_count_plan: number
  need_overseas_days_count_prog: number
  need_overseas_pay_plan: number
  need_overseas_pay_prog: number
  need_p_price_plan: number
  need_p_price_prog: number
  need_pay_plan: number
  need_pay_prog: number
  need_start_date_plan: string
  need_start_date_prog: string
  need_t_price_plan: number
  need_t_price_prog: number
  need_taxi_plan: number
  need_taxi_price_plan: number
  need_taxi_price_prog: number
  need_taxi_prog: number
  need_total_days_count_plan: number
  need_total_days_count_prog: number
  need_train_plan: string
  need_train_prog: string
  pc: number
  plan_price: number
  prog_price: number
  start_month: number
  start_year: number
  state: string
  trip_type_name: string
  year_plan_price_total: number
  id?: number
}
