import type { TprConnection } from '../contracts-entities/tpr-connection.interface'

export interface TprStandart {
  ID: number
  id_CalendarPlan: number
  name_CalendarPlan: string
  start_CalendarPlan: string
  finish_CalendarPlan: string
  dateConclusionContractPlan_CalendarPlan: string
  dateConclusionContractFact_CalendarPlan: string
  internalOrder_CalendarPlan: string
  risk_CalendarPlan: boolean
  genwork_CalendarPlan: boolean
  opex_CalendarPlan: boolean
  parentId_CalendarPlan: number
  totalContract_CalendarPlan: number
  numberContractId_CalendarPlan: number
  statusCalendarPlanId_CalendarPlan: number
  ndsId_CalendarPlan: number
  numberContract_None: string
  statusCalendarPlan_None: string
  nds_None: number
  id_CommentBlock: number | null
  status_CommentBlock: string
  general_CommentBlock: string
  deviationContract_CommentBlock: string
  deviationPlan_CommentBlock: string
  rate_CommentBlock: string
  id_Staff_Project: number
  department_Staff_Project: string
  customer_Staff_Project: string
  techCustomer_Staff_Project: string
  techCustomerDepartment_Staff_Project: string
  curator_None: string
  outside_None: boolean
  id_Business_Project: number
  kindWork_Business_Project: string
  directWork_Business_Project: string
  kindWorkId_None: number
  mounth1_id: number
  plancp_mounth1_id: number
  general_mounth1_plan_None: number
  general_mounth1_planCp_None: number
  general_mounth1_price_Stage: number
  general_mounth1_correction_Stage: number
  general_mounth1_factPrice_Stage: number
  general_mounth1_econom_None: number
  general_mounth1_econombp_None: number
  general_mounth1_prognozbp_None: number
  general_mounth1_economprognoz_None: number
  own_mounth1_plan_None: number
  own_mounth1_planCp_None: number
  own_mounth1_price_Stage: number
  own_mounth1_correction_Stage: number
  own_mounth1_factPrice_Stage: number
  own_mounth1_econom_None: number
  own_mounth1_econombp_None: number
  own_mounth1_prognozbp_None: number
  own_mounth1_economprognoz_None: number
  sub_mounth1_plan_None: number
  sub_mounth1_planCp_None: number
  sub_mounth1_price_Stage: number
  sub_mounth1_correction_Stage: number
  sub_mounth1_factPrice_Stage: number
  sub_mounth1_econom_None: number
  sub_mounth1_econombp_None: number
  sub_mounth1_prognozbp_None: number
  sub_mounth1_economprognoz_None: number
  mounth2_id: number
  plancp_mounth2_id: number
  general_mounth2_plan_None: number
  general_mounth2_planCp_None: number
  general_mounth2_price_Stage: number
  general_mounth2_correction_Stage: number
  general_mounth2_factPrice_Stage: number
  general_mounth2_econom_None: number
  general_mounth2_econombp_None: number
  general_mounth2_prognozbp_None: number
  general_mounth2_economprognoz_None: number
  own_mounth2_plan_None: number
  own_mounth2_planCp_None: number
  own_mounth2_price_Stage: number
  own_mounth2_correction_Stage: number
  own_mounth2_factPrice_Stage: number
  own_mounth2_econom_None: number
  own_mounth2_econombp_None: number
  own_mounth2_prognozbp_None: number
  own_mounth2_economprognoz_None: number
  sub_mounth2_plan_None: number
  sub_mounth2_planCp_None: number
  sub_mounth2_price_Stage: number
  sub_mounth2_correction_Stage: number
  sub_mounth2_factPrice_Stage: number
  sub_mounth2_econom_None: number
  sub_mounth2_econombp_None: number
  sub_mounth2_prognozbp_None: number
  sub_mounth2_economprognoz_None: number
  mounth3_id: number
  plancp_mounth3_id: number
  general_mounth3_plan_None: number
  general_mounth3_planCp_None: number
  general_mounth3_price_Stage: number
  general_mounth3_correction_Stage: number
  general_mounth3_factPrice_Stage: number
  general_mounth3_econom_None: number
  general_mounth3_econombp_None: number
  general_mounth3_prognozbp_None: number
  general_mounth3_economprognoz_None: number
  own_mounth3_plan_None: number
  own_mounth3_planCp_None: number
  own_mounth3_price_Stage: number
  own_mounth3_correction_Stage: number
  own_mounth3_factPrice_Stage: number
  own_mounth3_econom_None: number
  own_mounth3_econombp_None: number
  own_mounth3_prognozbp_None: number
  own_mounth3_economprognoz_None: number
  sub_mounth3_plan_None: number
  sub_mounth3_planCp_None: number
  sub_mounth3_price_Stage: number
  sub_mounth3_correction_Stage: number
  sub_mounth3_factPrice_Stage: number
  sub_mounth3_econom_None: number
  sub_mounth3_econombp_None: number
  sub_mounth3_prognozbp_None: number
  sub_mounth3_economprognoz_None: number
  mounth4_id: number
  plancp_mounth4_id: number
  general_mounth4_plan_None: number
  general_mounth4_planCp_None: number
  general_mounth4_price_Stage: number
  general_mounth4_correction_Stage: number
  general_mounth4_factPrice_Stage: number
  general_mounth4_econom_None: number
  general_mounth4_econombp_None: number
  general_mounth4_prognozbp_None: number
  general_mounth4_economprognoz_None: number
  own_mounth4_plan_None: number
  own_mounth4_planCp_None: number
  own_mounth4_price_Stage: number
  own_mounth4_correction_Stage: number
  own_mounth4_factPrice_Stage: number
  own_mounth4_econom_None: number
  own_mounth4_econombp_None: number
  own_mounth4_prognozbp_None: number
  own_mounth4_economprognoz_None: number
  sub_mounth4_plan_None: number
  sub_mounth4_planCp_None: number
  sub_mounth4_price_Stage: number
  sub_mounth4_correction_Stage: number
  sub_mounth4_factPrice_Stage: number
  sub_mounth4_econom_None: number
  sub_mounth4_econombp_None: number
  sub_mounth4_prognozbp_None: number
  sub_mounth4_economprognoz_None: number
  mounth5_id: number
  plancp_mounth5_id: number
  general_mounth5_plan_None: number
  general_mounth5_planCp_None: number
  general_mounth5_price_Stage: number
  general_mounth5_correction_Stage: number
  general_mounth5_factPrice_Stage: number
  general_mounth5_econom_None: number
  general_mounth5_econombp_None: number
  general_mounth5_prognozbp_None: number
  general_mounth5_economprognoz_None: number
  own_mounth5_plan_None: number
  own_mounth5_planCp_None: number
  own_mounth5_price_Stage: number
  own_mounth5_correction_Stage: number
  own_mounth5_factPrice_Stage: number
  own_mounth5_econom_None: number
  own_mounth5_econombp_None: number
  own_mounth5_prognozbp_None: number
  own_mounth5_economprognoz_None: number
  sub_mounth5_plan_None: number
  sub_mounth5_planCp_None: number
  sub_mounth5_price_Stage: number
  sub_mounth5_correction_Stage: number
  sub_mounth5_factPrice_Stage: number
  sub_mounth5_econom_None: number
  sub_mounth5_econombp_None: number
  sub_mounth5_prognozbp_None: number
  sub_mounth5_economprognoz_None: number
  mounth6_id: number
  plancp_mounth6_id: number
  general_mounth6_plan_None: number
  general_mounth6_planCp_None: number
  general_mounth6_price_Stage: number
  general_mounth6_correction_Stage: number
  general_mounth6_factPrice_Stage: number
  general_mounth6_econom_None: number
  general_mounth6_econombp_None: number
  general_mounth6_prognozbp_None: number
  general_mounth6_economprognoz_None: number
  own_mounth6_plan_None: number
  own_mounth6_planCp_None: number
  own_mounth6_price_Stage: number
  own_mounth6_correction_Stage: number
  own_mounth6_factPrice_Stage: number
  own_mounth6_econom_None: number
  own_mounth6_econombp_None: number
  own_mounth6_prognozbp_None: number
  own_mounth6_economprognoz_None: number
  sub_mounth6_plan_None: number
  sub_mounth6_planCp_None: number
  sub_mounth6_price_Stage: number
  sub_mounth6_correction_Stage: number
  sub_mounth6_factPrice_Stage: number
  sub_mounth6_econom_None: number
  sub_mounth6_econombp_None: number
  sub_mounth6_prognozbp_None: number
  sub_mounth6_economprognoz_None: number
  mounth7_id: number
  plancp_mounth7_id: number
  general_mounth7_plan_None: number
  general_mounth7_planCp_None: number
  general_mounth7_price_Stage: number
  general_mounth7_correction_Stage: number
  general_mounth7_factPrice_Stage: number
  general_mounth7_econom_None: number
  general_mounth7_econombp_None: number
  general_mounth7_prognozbp_None: number
  general_mounth7_economprognoz_None: number
  own_mounth7_plan_None: number
  own_mounth7_planCp_None: number
  own_mounth7_price_Stage: number
  own_mounth7_correction_Stage: number
  own_mounth7_factPrice_Stage: number
  own_mounth7_econom_None: number
  own_mounth7_econombp_None: number
  own_mounth7_prognozbp_None: number
  own_mounth7_economprognoz_None: number
  sub_mounth7_plan_None: number
  sub_mounth7_planCp_None: number
  sub_mounth7_price_Stage: number
  sub_mounth7_correction_Stage: number
  sub_mounth7_factPrice_Stage: number
  sub_mounth7_econom_None: number
  sub_mounth7_econombp_None: number
  sub_mounth7_prognozbp_None: number
  sub_mounth7_economprognoz_None: number
  mounth8_id: number
  plancp_mounth8_id: number
  general_mounth8_plan_None: number
  general_mounth8_planCp_None: number
  general_mounth8_price_Stage: number
  general_mounth8_correction_Stage: number
  general_mounth8_factPrice_Stage: number
  general_mounth8_econom_None: number
  general_mounth8_econombp_None: number
  general_mounth8_prognozbp_None: number
  general_mounth8_economprognoz_None: number
  own_mounth8_plan_None: number
  own_mounth8_planCp_None: number
  own_mounth8_price_Stage: number
  own_mounth8_correction_Stage: number
  own_mounth8_factPrice_Stage: number
  own_mounth8_econom_None: number
  own_mounth8_econombp_None: number
  own_mounth8_prognozbp_None: number
  own_mounth8_economprognoz_None: number
  sub_mounth8_plan_None: number
  sub_mounth8_planCp_None: number
  sub_mounth8_price_Stage: number
  sub_mounth8_correction_Stage: number
  sub_mounth8_factPrice_Stage: number
  sub_mounth8_econom_None: number
  sub_mounth8_econombp_None: number
  sub_mounth8_prognozbp_None: number
  sub_mounth8_economprognoz_None: number
  mounth9_id: number
  plancp_mounth9_id: number
  general_mounth9_plan_None: number
  general_mounth9_planCp_None: number
  general_mounth9_price_Stage: number
  general_mounth9_correction_Stage: number
  general_mounth9_factPrice_Stage: number
  general_mounth9_econom_None: number
  general_mounth9_econombp_None: number
  general_mounth9_prognozbp_None: number
  general_mounth9_economprognoz_None: number
  own_mounth9_plan_None: number
  own_mounth9_planCp_None: number
  own_mounth9_price_Stage: number
  own_mounth9_correction_Stage: number
  own_mounth9_factPrice_Stage: number
  own_mounth9_econom_None: number
  own_mounth9_econombp_None: number
  own_mounth9_prognozbp_None: number
  own_mounth9_economprognoz_None: number
  sub_mounth9_plan_None: number
  sub_mounth9_planCp_None: number
  sub_mounth9_price_Stage: number
  sub_mounth9_correction_Stage: number
  sub_mounth9_factPrice_Stage: number
  sub_mounth9_econom_None: number
  sub_mounth9_econombp_None: number
  sub_mounth9_prognozbp_None: number
  sub_mounth9_economprognoz_None: number
  mounth1number_id: number
  plancp_mounth1number_id: number
  general_mounth1number_plan_None: number
  general_mounth1number_planCp_None: number
  general_mounth1number_price_Stage: number
  general_mounth1number_correction_Stage: number
  general_mounth1number_factPrice_Stage: number
  general_mounth1number_econom_None: number
  general_mounth1number_econombp_None: number
  general_mounth1number_prognozbp_None: number
  general_mounth1number_economprognoz_None: number
  own_mounth1number_plan_None: number
  own_mounth1number_planCp_None: number
  own_mounth1number_price_Stage: number
  own_mounth1number_correction_Stage: number
  own_mounth1number_factPrice_Stage: number
  own_mounth1number_econom_None: number
  own_mounth1number_econombp_None: number
  own_mounth1number_prognozbp_None: number
  own_mounth1number_economprognoz_None: number
  sub_mounth1number_plan_None: number
  sub_mounth1number_planCp_None: number
  sub_mounth1number_price_Stage: number
  sub_mounth1number_correction_Stage: number
  sub_mounth1number_factPrice_Stage: number
  sub_mounth1number_econom_None: number
  sub_mounth1number_econombp_None: number
  sub_mounth1number_prognozbp_None: number
  sub_mounth1number_economprognoz_None: number
  mounth11_id: number
  plancp_mounth11_id: number
  general_mounth11_plan_None: number
  general_mounth11_planCp_None: number
  general_mounth11_price_Stage: number
  general_mounth11_correction_Stage: number
  general_mounth11_factPrice_Stage: number
  general_mounth11_econom_None: number
  general_mounth11_econombp_None: number
  general_mounth11_prognozbp_None: number
  general_mounth11_economprognoz_None: number
  own_mounth11_plan_None: number
  own_mounth11_planCp_None: number
  own_mounth11_price_Stage: number
  own_mounth11_correction_Stage: number
  own_mounth11_factPrice_Stage: number
  own_mounth11_econom_None: number
  own_mounth11_econombp_None: number
  own_mounth11_prognozbp_None: number
  own_mounth11_economprognoz_None: number
  sub_mounth11_plan_None: number
  sub_mounth11_planCp_None: number
  sub_mounth11_price_Stage: number
  sub_mounth11_correction_Stage: number
  sub_mounth11_factPrice_Stage: number
  sub_mounth11_econom_None: number
  sub_mounth11_econombp_None: number
  sub_mounth11_prognozbp_None: number
  sub_mounth11_economprognoz_None: number
  mounth12_id: number
  plancp_mounth12_id: number
  general_mounth12_plan_None: number
  general_mounth12_planCp_None: number
  general_mounth12_price_Stage: number
  general_mounth12_correction_Stage: number
  general_mounth12_factPrice_Stage: number
  general_mounth12_econom_None: number
  general_mounth12_econombp_None: number
  general_mounth12_prognozbp_None: number
  general_mounth12_economprognoz_None: number
  own_mounth12_plan_None: number
  own_mounth12_planCp_None: number
  own_mounth12_price_Stage: number
  own_mounth12_correction_Stage: number
  own_mounth12_factPrice_Stage: number
  own_mounth12_econom_None: number
  own_mounth12_econombp_None: number
  own_mounth12_prognozbp_None: number
  own_mounth12_economprognoz_None: number
  sub_mounth12_plan_None: number
  sub_mounth12_planCp_None: number
  sub_mounth12_price_Stage: number
  sub_mounth12_correction_Stage: number
  sub_mounth12_factPrice_Stage: number
  sub_mounth12_econom_None: number
  sub_mounth12_econombp_None: number
  sub_mounth12_prognozbp_None: number
  sub_mounth12_economprognoz_None: number
  generalEplan_None: number
  generalEplanCp_None: number
  generalEprice_Stage: number
  generalEfactPrice_Stage: number
  generalEeconom_None: number
  generalEeconombp_None: number
  generalEprognozbp_None: number
  generalEeconomprognoz_None: number
  subEplan_None: number
  subEplanCp_None: number
  subEprice_Stage: number
  subEfactPrice_Stage: number
  subEeconom_None: number
  subEeconombp_None: number
  subEprognozbp_None: number
  subEeconomprognoz_None: number
  ownEplan_None: number
  ownEplanCp_None: number
  ownEprice_Stage: number
  ownEfactPrice_Stage: number
  ownEeconom_None: number
  ownEeconombp_None: number
  ownEprognozbp_None: number
  ownEeconomprognoz_None: number
  id_GeneralForcesFactor: number
  generalDeviation_None: number
  discountEconomySelf_GeneralForcesFactor: number
  cancellWork_GeneralForcesFactor: number
  transferWork_GeneralForcesFactor: number
  revisionWork_GeneralForcesFactor: number
  closeCosts_GeneralForcesFactor: number
  reduceTender_GeneralForcesFactor: number
  operationKNIPI_GeneralForcesFactor: number
  comments_GeneralForcesFactor: string
  id_OwnForcesFactor: number
  ownDeviation_None: number
  discountEconomySelf_OwnForcesFactor: number
  cancellWork_OwnForcesFactor: number
  transferWork_OwnForcesFactor: number
  revisionWork_OwnForcesFactor: number
  moveSelf_OwnForcesFactor: number
  operationKNIPI_OwnForcesFactor: number
  comments_OwnForcesFactor: string
  id_ReasonTransferWorkExternalSub: number
  completeMailKNIPI_ReasonTransferWorkExternalSub: string
  dateMailCommercialOffer_ReasonTransferWorkExternalSub: string
  refusalKNIPI_ReasonTransferWorkExternalSub: string
  reasonTransferExternalSub_ReasonTransferWorkExternalSub: string
  contractConclusionFormat_ReasonTransferWorkExternalSub: string
  approveDPR_ReasonTransferWorkExternalSub: boolean
  approveGI_ReasonTransferWorkExternalSub: boolean
  comments_ReasonTransferWorkExternalSub: string
  id_GhostCalendarPlan: number
  cIP_GhostCalendarPlan: number
  monitoringUnplannedWork_GhostCalendarPlan: string
  timeConstraints_GhostCalendarPlan: string
  formatGeneralContractOutsideCustomerId_GhostCalendarPlan: number
  formatGeneralContractOutsideCustomer_None: string
  scopeWorkSubcontractId_GhostCalendarPlan: number
  scopeWorkSubcontract_None: string
  reasonWorkSubcontractId_GhostCalendarPlan: number
  reasonWorkSubcontract_None: string
  id_NumberCalendarPlanOfYear: number
  uniqueIdNumberOfYear_NumberCalendarPlanOfYear: number
  okved_None: string
  connection?: TprConnection
  subs?: TprStandart[]
  parentContract_None: string
  note_CommentBlock: string
}
